version: "2"
services:
    nginx:
        build:
            context: nginx
            dockerfile: Dockerfile
        image: treylitefm/nginx
        links:
            - hermes
        ports:
            - "80:80"
        volumes:
            - ./main/src:/var/www/hermes
    hermes:
        container_name: hermes
        build:
            context: main
            dockerfile: Dockerfile
        image: treylitefm/hermes
        volumes:
            - $PWD/main/src:/var/hermes
        ports:
            - "8000:8000"
        links:
            - postgres
        depends_on:
            - postgres
    test_app:
        container_name: flask_test_app
        build: 
            context: test_app
            dockerfile: Dockerfile
        image: treylitefm/flask_test_app
        ports:
            - "5000:5000"
        volumes:
            - $PWD/test_app/src:/var/test_app
        entrypoint: python server.py
    postgres:
        container_name: postgres-server
        image: postgres
        ports: 
            - "5432:5432"
networks:
    default:
        external:
            name: hermes
