# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-29 22:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('launchpad', '0006_auto_20160929_2211'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.SmallIntegerField(choices=[(0, 'QUEUED'), (1, 'IN PROGRESS'), (2, 'PASS'), (3, 'FAIL')], default=0)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='launchpad.Page')),
            ],
            options={
                'db_table': 'tests',
            },
        ),
    ]
