# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-29 23:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='screenshot_url',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='test',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'QUEUED'), (1, 'IN PROGRESS'), (2, 'PASS'), (3, 'FAIL'), (4, 'ERROR')], default=0),
        ),
    ]
