# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-29 23:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0002_auto_20160929_2355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='screenshot_url',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
