# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-30 02:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0004_auto_20160930_0050'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='test',
            options={'ordering': ['created_on']},
        ),
    ]
