# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-30 05:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0005_auto_20160930_0259'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='test',
            options={'get_latest_by': 'created_on', 'ordering': ['created_on']},
        ),
    ]
