# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-30 06:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0006_auto_20160929_2247'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='browser',
            field=models.SmallIntegerField(choices=[(0, 'FIREFOX'), (1, 'CHROME')], default=0),
        ),
    ]
