# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-28 02:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('launchpad', '0003_auto_20160928_0230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='protocol',
            field=models.SmallIntegerField(choices=[(0, 'http'), (1, 'https')], default=0),
        ),
        migrations.AlterField(
            model_name='page',
            name='ping_health',
            field=models.SmallIntegerField(choices=[(1, 'Green'), (3, 'Yellow'), (5, 'Red')], default=1),
        ),
        migrations.AlterField(
            model_name='testrun',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'Green'), (3, 'Yellow'), (5, 'Red')], default=1),
        ),
    ]
