# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-28 03:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('launchpad', '0004_auto_20160928_0253'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='page',
            name='enabled',
            field=models.BooleanField(default=False),
        ),
    ]
