# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-29 22:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('launchpad', '0005_auto_20160928_0324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testrun',
            name='page',
        ),
        migrations.RemoveField(
            model_name='page',
            name='ping_health',
        ),
        migrations.DeleteModel(
            name='TestRun',
        ),
    ]
