# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-30 02:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('launchpad', '0006_auto_20160929_2211'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='app',
            options={'ordering': ['created_on']},
        ),
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['created_on']},
        ),
    ]
